In [4]:
import nasdaqdatalink
import quandl
mydata = quandl.get("MULTPL/SHILLER_PE_RATIO_MONTH")

In [7]:
mydata

            Value
Date
1871-02-01  10.92
1871-03-01  11.19
1871-04-01  12.05
1871-05-01  12.59
1871-06-01  12.59
...           ...
2022-01-01  37.47
2022-01-31  37.31
2022-02-01  37.54
2022-02-28  35.80
2022-03-01  35.25

[1835 rows x 1 columns]

In [76]:
myNewData = mydata.reset_index()

In [77]:
s = ""
for i in range(len(myNewData)):
  if i == 0:
    #print("[")
    s = s + "["
  #print("[" + str(myNewData.loc[i, "Date"].timestamp() * 1000) + ", " +  str(myNewData.loc[i, "Value"]) + "],")
  s = s + "[" + str(myNewData.loc[i, "Date"].timestamp() * 1000) + ", " +  str(myNewData.loc[i, "Value"]) + "],"

In [78]:
s = s[:-1]
s = s + "]"
s

'[[-3121459200000.0, 10.92],[-3119040000000.0, 11.19],[-3116361600000.0, 12.05],[-3113769600000.0, 12.59],[-3111091200000.0, 12.59],[-3108499200000.0, 12.27],[-3105820800000.0, 12.55],[-3103142400000.0, 12.31],[-3100550400000.0, 11.47],[-3097872000000.0, 11.6],[-3095280000000.0, 11.59],[-3092601600000.0, 11.9],[-3089923200000.0, 11.96],[-3087417600000.0, 12.18],[-3084739200000.0, 12.25],[-3082147200000.0, 12.28],[-3079468800000.0, 12.27],[-3076876800000.0, 12.38],[-3074198400000.0, 12.13],[-3071520000000.0, 11.83],[-3068928000000.0, 12.13],[-3066249600000.0, 11.71],[-3063657600000.0, 12.17],[-3060979200000.0, 12.25],[-3058300800000.0, 12.05],[-3055881600000.0, 11.95],[-3053203200000.0, 11.78],[-3050611200000.0, 12.05],[-3047932800000.0, 12.22],[-3045340800000.0, 12.16],[-3042662400000.0, 12.12],[-3039984000000.0, 11.16],[-3037392000000.0, 10.4],[-3034713600000.0, 10.31],[-3032121600000.0, 10.96],[-3029443200000.0, 11.33],[-3026764800000.0, 11.63],[-3024345600000.0, 11.43],[-3021667200000.0, 11.26],[-3019075200000.0, 11.02],[-3016396800000.0, 11.19],[-3013804800000.0, 11.07],[-3011126400000.0, 11.14],[-3008448000000.0, 11.28],[-3005856000000.0, 11.4],[-3003177600000.0, 11.56],[-3000585600000.0, 11.45],[-2997907200000.0, 11.41],[-2995228800000.0, 11.35],[-2992809600000.0, 11.48],[-2990131200000.0, 11.51],[-2987539200000.0, 11.33],[-2984860800000.0, 11.28],[-2982268800000.0, 11.29],[-2979590400000.0, 11.24],[-2976912000000.0, 11.24],[-2974320000000.0, 11.06],[-2971641600000.0, 11.34],[-2969049600000.0, 11.45],[-2966371200000.0, 11.79],[-2963692800000.0, 11.96],[-2961187200000.0, 11.95],[-2958508800000.0, 11.63],[-2955916800000.0, 11.63],[-2953238400000.0, 11.88],[-2950646400000.0, 11.75],[-2947968000000.0, 11.18],[-2945289600000.0, 10.42],[-2942697600000.0, 10.2],[-2940019200000.0, 9.94],[-2937427200000.0, 9.74],[-2934748800000.0, 9.52],[-2932070400000.0, 9.23],[-2929651200000.0, 9.2],[-2926972800000.0, 8.31],[-2924380800000.0, 8.18],[-2921702400000.0, 8.05],[-2919110400000.0, 8.35],[-2916432000000.0, 9.29],[-2913753600000.0, 9.99],[-2911161600000.0, 10.22],[-2908483200000.0, 10.27],[-2905891200000.0, 10.25],[-2903212800000.0, 10.57],[-2900534400000.0, 10.45],[-2898115200000.0, 10.88],[-2895436800000.0, 11.29],[-2892844800000.0, 11.71],[-2890166400000.0, 12.21],[-2887574400000.0, 12.31],[-2884896000000.0, 12.06],[-2882217600000.0, 12.3],[-2879625600000.0, 12.28],[-2876947200000.0, 12.37],[-2874355200000.0, 12.58],[-2871676800000.0, 12.87],[-2868998400000.0, 13.18],[-2866579200000.0, 13.09],[-2863900800000.0, 13.66],[-2861308800000.0, 14.25],[-2858630400000.0, 14.45],[-2856038400000.0, 14.54],[-2853360000000.0, 14.61],[-2850681600000.0, 14.59],[-2848089600000.0, 15.29],[-2845411200000.0, 15.26],[-2842819200000.0, 14.77],[-2840140800000.0, 14.87],[-2837462400000.0, 15.12],[-2834956800000.0, 15.23],[-2832278400000.0, 15.46],[-2829686400000.0, 14.63],[-2827008000000.0, 14.95],[-2824416000000.0, 15.59],[-2821737600000.0, 16.1],[-2819059200000.0, 15.86],[-2816467200000.0, 16.26],[-2813788800000.0, 16.87],[-2811196800000.0, 17.33],[-2808518400000.0, 18.47],[-2805840000000.0, 18.15],[-2803420800000.0, 18.28],[-2800742400000.0, 17.95],[-2798150400000.0, 18.88],[-2795472000000.0, 19.04],[-2792880000000.0, 18.11],[-2790201600000.0, 17.28],[-2787523200000.0, 16.72],[-2784931200000.0, 16.25],[-2782252800000.0, 16.48],[-2779660800000.0, 15.96],[-2776982400000.0, 15.68],[-2774304000000.0, 15.15],[-2771884800000.0, 15.08],[-2769206400000.0, 14.92],[-2766614400000.0, 14.56],[-2763936000000.0, 14.33],[-2761344000000.0, 15.23],[-2758665600000.0, 15.53],[-2755987200000.0, 16.07],[-2753395200000.0, 15.76],[-2750716800000.0, 15.19],[-2748124800000.0, 15.38],[-2745446400000.0, 15.27],[-2742768000000.0, 14.75],[-2740348800000.0, 15.05],[-2737670400000.0, 15.47],[-2735078400000.0, 15.33],[-2732400000000.0, 15.91],[-2729808000000.0, 15.96],[-2727129600000.0, 15.2],[-2724451200000.0, 15.49],[-2721859200000.0, 15.05],[-2719180800000.0, 15.41],[-2716588800000.0, 14.89],[-2713910400000.0, 14.43],[-2711232000000.0, 14.8],[-2708726400000.0, 14.73],[-2706048000000.0, 14.35],[-2703456000000.0, 13.46],[-2700777600000.0, 12.9],[-2698185600000.0, 13.05],[-2695507200000.0, 13.86],[-2692828800000.0, 13.57],[-2690236800000.0, 13.28],[-2687558400000.0, 13.31],[-2684966400000.0, 13.43],[-2682288000000.0, 13.13],[-2679609600000.0, 13.39],[-2677190400000.0, 13.74],[-2674512000000.0, 13.54],[-2671920000000.0, 13.71],[-2669241600000.0, 13.97],[-2666649600000.0, 14.33],[-2663971200000.0, 15.13],[-2661292800000.0, 15.11],[-2658700800000.0, 15.98],[-2656022400000.0, 16.83],[-2653430400000.0, 16.31],[-2650752000000.0, 16.7],[-2648073600000.0, 17.01],[-2645654400000.0, 16.84],[-2642976000000.0, 16.81],[-2640384000000.0, 16.87],[-2637705600000.0, 17.82],[-2635113600000.0, 17.85],[-2632435200000.0, 17.72],[-2629756800000.0, 18.14],[-2627164800000.0, 18.55],[-2624486400000.0, 18.96],[-2621894400000.0, 18.2],[-2619216000000.0, 17.52],[-2616537600000.0, 17.12],[-2614118400000.0, 17.47],[-2611440000000.0, 17.82],[-2608848000000.0, 18.07],[-2606169600000.0, 17.71],[-2603577600000.0, 17.42],[-2600899200000.0, 16.74],[-2598220800000.0, 16.67],[-2595628800000.0, 15.88],[-2592950400000.0, 15.95],[-2590358400000.0, 15.45],[-2587680000000.0, 15.36],[-2585001600000.0, 15.41],[-2582496000000.0, 14.8],[-2579817600000.0, 15.02],[-2577225600000.0, 15.38],[-2574547200000.0, 15.08],[-2571955200000.0, 15.27],[-2569276800000.0, 15.6],[-2566598400000.0, 15.98],[-2564006400000.0, 15.72],[-2561328000000.0, 15.22],[-2558736000000.0, 14.94],[-2556057600000.0, 15.81],[-2553379200000.0, 16.19],[-2550960000000.0, 16.07],[-2548281600000.0, 16.05],[-2545689600000.0, 16.92],[-2543011200000.0, 17.22],[-2540419200000.0, 16.89],[-2537740800000.0, 17.14],[-2535062400000.0, 17.34],[-2532470400000.0, 17.05],[-2529792000000.0, 16.9],[-2527200000000.0, 16.61],[-2524521600000.0, 17.22],[-2521843200000.0, 17.03],[-2519424000000.0, 16.9],[-2516745600000.0, 17.26],[-2514153600000.0, 17.78],[-2511475200000.0, 17.68],[-2508883200000.0, 17.58],[-2506204800000.0, 16.6],[-2503526400000.0, 16.16],[-2500934400000.0, 15.48],[-2498256000000.0, 14.74],[-2495664000000.0, 14.44],[-2492985600000.0, 15.43],[-2490307200000.0, 15.47],[-2487888000000.0, 15.06],[-2485209600000.0, 15.4],[-2482617600000.0, 15.57],[-2479939200000.0, 15.66],[-2477347200000.0, 15.61],[-2474668800000.0, 16.16],[-2471990400000.0, 17.72],[-2469398400000.0, 17.72],[-2466720000000.0, 17.66],[-2464128000000.0, 18.2],[-2461449600000.0, 19.01],[-2458771200000.0, 19.03],[-2456265600000.0, 19.73],[-2453587200000.0, 19.95],[-2450995200000.0, 19.92],[-2448316800000.0, 19.77],[-2445724800000.0, 19.22],[-2443046400000.0, 19.2],[-2440368000000.0, 18.69],[-2437776000000.0, 19.03],[-2435097600000.0, 18.46],[-2432505600000.0, 18.02],[-2429827200000.0, 17.65],[-2427148800000.0, 17.13],[-2424729600000.0, 16.9],[-2422051200000.0, 17.1],[-2419459200000.0, 15.79],[-2416780800000.0, 15.42],[-2414188800000.0, 14.35],[-2411510400000.0, 14.58],[-2408832000000.0, 15.02],[-2406240000000.0, 15.27],[-2403561600000.0, 15.93],[-2400969600000.0, 15.62],[-2398291200000.0, 15.74],[-2395612800000.0, 16.19],[-2393193600000.0, 17.18],[-2390515200000.0, 17.42],[-2387923200000.0, 16.8],[-2385244800000.0, 16.6],[-2382652800000.0, 16.28],[-2379974400000.0, 16.45],[-2377296000000.0, 16.53],[-2374704000000.0, 16.51],[-2372025600000.0, 16.55],[-2369433600000.0, 16.66],[-2366755200000.0, 16.51],[-2364076800000.0, 16.32],[-2361657600000.0, 16.35],[-2358979200000.0, 16.39],[-2356387200000.0, 17.07],[-2353708800000.0, 17.21],[-2351116800000.0, 17.54],[-2348438400000.0, 18.08],[-2345760000000.0, 18.2],[-2343168000000.0, 17.95],[-2340489600000.0, 17.35],[-2337897600000.0, 16.54],[-2335219200000.0, 16.58],[-2332540800000.0, 17.5],[-2330035200000.0, 17.22],[-2327356800000.0, 17.65],[-2324764800000.0, 17.84],[-2322086400000.0, 17.78],[-2319494400000.0, 16.64],[-2316816000000.0, 15.7],[-2314137600000.0, 16.55],[-2311545600000.0, 16.44],[-2308867200000.0, 17.09],[-2306275200000.0, 16.5],[-2303596800000.0, 17.03],[-2300918400000.0, 16.9],[-2298499200000.0, 16.96],[-2295820800000.0, 16.71],[-2293228800000.0, 17.05],[-2290550400000.0, 17.85],[-2287958400000.0, 18.65],[-2285280000000.0, 18.99],[-2282601600000.0, 19.36],[-2280009600000.0, 19.03],[-2277331200000.0, 18.36],[-2274739200000.0, 18.75],[-2272060800000.0, 19.25],[-2269382400000.0, 18.91],[-2266963200000.0, 18.03],[-2264284800000.0, 17.7],[-2261692800000.0, 17.6],[-2259014400000.0, 19.53],[-2256422400000.0, 19.86],[-2253744000000.0, 20.55],[-2251065600000.0, 20.45],[-2248473600000.0, 19.95],[-2245795200000.0, 20.53],[-2243203200000.0, 21.39],[-2240524800000.0, 22.92],[-2237846400000.0, 23.04],[-2235427200000.0, 23.27],[-2232748800000.0, 23.16],[-2230156800000.0, 22.1],[-2227478400000.0, 21.2],[-2224886400000.0, 21.57],[-2222208000000.0, 21.72],[-2219529600000.0, 20.6],[-2216937600000.0, 20.15],[-2214259200000.0, 20.21],[-2211667200000.0, 18.51],[-2208988800000.0, 18.67],[-2206310400000.0, 18.71],[-2203891200000.0, 18.78],[-2201212800000.0, 18.95],[-2198620800000.0, 18.41],[-2195942400000.0, 17.99],[-2193350400000.0, 17.7],[-2190672000000.0, 18.07],[-2187993600000.0, 17.35],[-2185401600000.0, 18.1],[-2182723200000.0, 19.42],[-2180131200000.0, 20.75],[-2177452800000.0, 20.97],[-2174774400000.0, 21.69],[-2172355200000.0, 22.36],[-2169676800000.0, 24.4],[-2167084800000.0, 23.06],[-2164406400000.0, 25.23],[-2161814400000.0, 23.15],[-2159136000000.0, 23.07],[-2156457600000.0, 22.6],[-2153865600000.0, 22.26],[-2151187200000.0, 22.37],[-2148595200000.0, 21.69],[-2145916800000.0, 22.34],[-2143238400000.0, 22.46],[-2140819200000.0, 22.41],[-2138140800000.0, 22.83],[-2135548800000.0, 22.42],[-2132870400000.0, 21.97],[-2130278400000.0, 22.4],[-2127600000000.0, 23.17],[-2124921600000.0, 22.87],[-2122329600000.0, 20.62],[-2119651200000.0, 20.41],[-2117059200000.0, 19.64],[-2114380800000.0, 20.32],[-2111702400000.0, 20.11],[-2109283200000.0, 19.89],[-2106604800000.0, 18.99],[-2104012800000.0, 18.96],[-2101334400000.0, 17.83],[-2098742400000.0, 16.93],[-2096064000000.0, 16.31],[-2093385600000.0, 15.65],[-2090793600000.0, 15.26],[-2088115200000.0, 15.4],[-2085523200000.0, 16.04],[-2082844800000.0, 15.86],[-2080166400000.0, 15.02],[-2077660800000.0, 15.09],[-2074982400000.0, 15.56],[-2072390400000.0, 15.52],[-2069712000000.0, 15.47],[-2067120000000.0, 16.03],[-2064441600000.0, 16.31],[-2061763200000.0, 16.74],[-2059171200000.0, 17.63],[-2056492800000.0, 18.07],[-2053900800000.0, 18.16],[-2051222400000.0, 18.46],[-2048544000000.0, 19.17],[-2046124800000.0, 19.84],[-2043446400000.0, 19.49],[-2040854400000.0, 18.63],[-2038176000000.0, 18.73],[-2035584000000.0, 19.2],[-2032905600000.0, 19.58],[-2030227200000.0, 19.74],[-2027635200000.0, 19.89],[-2024956800000.0, 19.45],[-2022364800000.0, 19.57],[-2019686400000.0, 20.13],[-2017008000000.0, 19.86],[-2014588800000.0, 19.26],[-2011910400000.0, 18.87],[-2009318400000.0, 18.06],[-2006640000000.0, 18.18],[-2004048000000.0, 18.19],[-2001369600000.0, 18.96],[-1998691200000.0, 19.21],[-1996099200000.0, 18.1],[-1993420800000.0, 18.14],[-1990828800000.0, 17.67],[-1988150400000.0, 17.22],[-1985472000000.0, 16.22],[-1983052800000.0, 14.69],[-1980374400000.0, 14.68],[-1977782400000.0, 13.8],[-1975104000000.0, 13.14],[-1972512000000.0, 13.58],[-1969833600000.0, 12.51],[-1967155200000.0, 12.33],[-1964563200000.0, 10.84],[-1961884800000.0, 10.6],[-1959292800000.0, 11.34],[-1956614400000.0, 11.9],[-1953936000000.0, 11.56],[-1951430400000.0, 11.99],[-1948752000000.0, 12.45],[-1946160000000.0, 13.08],[-1943481600000.0, 13.05],[-1940889600000.0, 13.35],[-1938211200000.0, 13.89],[-1935532800000.0, 13.71],[-1932940800000.0, 13.69],[-1930262400000.0, 14.44],[-1927670400000.0, 14.58],[-1924992000000.0, 14.77],[-1922313600000.0, 14.17],[-1919894400000.0, 14.33],[-1917216000000.0, 14.64],[-1914624000000.0, 14.96],[-1911945600000.0, 15.04],[-1909353600000.0, 15.23],[-1906675200000.0, 15.43],[-1903996800000.0, 15.25],[-1901404800000.0, 14.99],[-1898726400000.0, 14.74],[-1896134400000.0, 14.75],[-1893456000000.0, 14.54],[-1890777600000.0, 14.0],[-1888358400000.0, 14.04],[-1885680000000.0, 13.56],[-1883088000000.0, 13.57],[-1880409600000.0, 13.01],[-1877817600000.0, 12.34],[-1875139200000.0, 12.75],[-1872460800000.0, 12.94],[-1869868800000.0, 13.92],[-1867190400000.0, 14.16],[-1864598400000.0, 13.74],[-1861920000000.0, 14.05],[-1859241600000.0, 14.73],[-1856822400000.0, 14.37],[-1854144000000.0, 14.76],[-1851552000000.0, 15.05],[-1848873600000.0, 15.33],[-1846281600000.0, 15.08],[-1843603200000.0, 13.91],[-1840924800000.0, 13.0],[-1838332800000.0, 13.07],[-1835654400000.0, 13.73],[-1833062400000.0, 13.93],[-1830384000000.0, 13.8],[-1827705600000.0, 13.53],[-1825200000000.0, 13.64],[-1822521600000.0, 13.66],[-1819929600000.0, 13.65],[-1817251200000.0, 13.78],[-1814659200000.0, 13.8],[-1811980800000.0, 13.99],[-1809302400000.0, 13.93],[-1806710400000.0, 13.9],[-1804032000000.0, 13.75],[-1801440000000.0, 13.4],[-1798761600000.0, 13.15],[-1796083200000.0, 12.68],[-1793664000000.0, 12.44],[-1790985600000.0, 12.43],[-1788393600000.0, 12.22],[-1785715200000.0, 11.49],[-1783123200000.0, 11.53],[-1780444800000.0, 11.85],[-1777766400000.0, 11.84],[-1775174400000.0, 11.47],[-1772496000000.0, 11.07],[-1769904000000.0, 11.17],[-1767225600000.0, 11.64],[-1764547200000.0, 11.91],[-1762128000000.0, 11.69],[-1759449600000.0, 11.52],[-1756857600000.0, 11.48],[-1754179200000.0, 11.43],[-1751587200000.0, 10.69],[-1748908800000.0, 10.49],[-1746230400000.0, 10.5],[-1743638400000.0, 10.61],[-1740960000000.0, 10.52],[-1738368000000.0, 10.17],[-1735689600000.0, 10.36],[-1733011200000.0, 10.33],[-1730592000000.0, 10.71],[-1727913600000.0, 11.4],[-1725321600000.0, 11.03],[-1722643200000.0, 11.15],[-1720051200000.0, 11.11],[-1717372800000.0, 11.58],[-1714694400000.0, 12.01],[-1712102400000.0, 12.55],[-1709424000000.0, 12.86],[-1706832000000.0, 12.88],[-1704153600000.0, 12.54],[-1701475200000.0, 12.35],[-1698969600000.0, 12.18],[-1696291200000.0, 11.91],[-1693699200000.0, 12.03],[-1691020800000.0, 12.0],[-1688428800000.0, 11.79],[-1685750400000.0, 11.73],[-1683072000000.0, 11.94],[-1680480000000.0, 12.05],[-1677801600000.0, 12.05],[-1675209600000.0, 11.41],[-1672531200000.0, 10.99],[-1669852800000.0, 10.06],[-1667433600000.0, 10.33],[-1664755200000.0, 9.64],[-1662163200000.0, 9.14],[-1659484800000.0, 9.15],[-1656892800000.0, 9.0],[-1654214400000.0, 8.57],[-1651536000000.0, 7.95],[-1648944000000.0, 7.39],[-1646265600000.0, 6.75],[-1643673600000.0, 6.41],[-1640995200000.0, 6.64],[-1638316800000.0, 6.78],[-1635897600000.0, 6.69],[-1633219200000.0, 6.52],[-1630627200000.0, 6.58],[-1627948800000.0, 6.5],[-1625356800000.0, 6.37],[-1622678400000.0, 6.3],[-1620000000000.0, 6.15],[-1617408000000.0, 6.29],[-1614729600000.0, 6.33],[-1612137600000.0, 6.13],[-1609459200000.0, 6.1],[-1606780800000.0, 6.24],[-1604361600000.0, 6.36],[-1601683200000.0, 6.46],[-1599091200000.0, 6.83],[-1596412800000.0, 7.02],[-1593820800000.0, 7.05],[-1591142400000.0, 6.48],[-1588464000000.0, 6.56],[-1585872000000.0, 6.79],[-1583193600000.0, 6.47],[-1580601600000.0, 6.16],[-1577923200000.0, 5.99],[-1575244800000.0, 5.46],[-1572739200000.0, 5.8],[-1570060800000.0, 5.6],[-1567468800000.0, 5.19],[-1564790400000.0, 5.04],[-1562198400000.0, 5.08],[-1559520000000.0, 5.02],[-1556841600000.0, 5.3],[-1554249600000.0, 5.35],[-1551571200000.0, 5.13],[-1548979200000.0, 4.78],[-1546300800000.0, 5.12],[-1543622400000.0, 5.27],[-1541203200000.0, 5.19],[-1538524800000.0, 5.3],[-1535932800000.0, 5.61],[-1533254400000.0, 5.22],[-1530662400000.0, 5.2],[-1527984000000.0, 5.16],[-1525305600000.0, 5.38],[-1522713600000.0, 5.48],[-1520035200000.0, 5.84],[-1517443200000.0, 6.11],[-1514764800000.0, 6.29],[-1512086400000.0, 6.46],[-1509667200000.0, 6.82],[-1506988800000.0, 7.27],[-1504396800000.0, 7.59],[-1501718400000.0, 7.56],[-1499126400000.0, 7.6],[-1496448000000.0, 8.02],[-1493769600000.0, 8.27],[-1491177600000.0, 8.43],[-1488499200000.0, 8.0],[-1485907200000.0, 7.96],[-1483228800000.0, 8.15],[-1480550400000.0, 8.53],[-1478131200000.0, 8.7],[-1475452800000.0, 8.37],[-1472860800000.0, 8.0],[-1470182400000.0, 7.67],[-1467590400000.0, 7.35],[-1464912000000.0, 7.44],[-1462233600000.0, 7.46],[-1459641600000.0, 7.32],[-1456963200000.0, 7.55],[-1454371200000.0, 7.81],[-1451692800000.0, 8.07],[-1449014400000.0, 8.16],[-1446508800000.0, 8.06],[-1443830400000.0, 7.92],[-1441238400000.0, 7.9],[-1438560000000.0, 8.05],[-1435968000000.0, 8.38],[-1433289600000.0, 8.72],[-1430611200000.0, 8.58],[-1428019200000.0, 8.42],[-1425340800000.0, 8.89],[-1422748800000.0, 9.31],[-1420070400000.0, 9.69],[-1417392000000.0, 9.83],[-1414972800000.0, 9.52],[-1412294400000.0, 9.48],[-1409702400000.0, 9.73],[-1407024000000.0, 9.8],[-1404432000000.0, 9.96],[-1401753600000.0, 10.11],[-1399075200000.0, 10.36],[-1396483200000.0, 10.72],[-1393804800000.0, 10.89],[-1391212800000.0, 11.15],[-1388534400000.0, 11.34],[-1385856000000.0, 11.39],[-1383436800000.0, 10.71],[-1380758400000.0, 10.4],[-1378166400000.0, 10.58],[-1375488000000.0, 11.2],[-1372896000000.0, 11.87],[-1370217600000.0, 12.49],[-1367539200000.0, 12.69],[-1364947200000.0, 12.43],[-1362268800000.0, 12.62],[-1359676800000.0, 13.01],[-1356998400000.0, 13.19],[-1354320000000.0, 13.63],[-1351900800000.0, 14.03],[-1349222400000.0, 14.49],[-1346630400000.0, 15.0],[-1343952000000.0, 15.12],[-1341360000000.0, 15.82],[-1338681600000.0, 16.86],[-1336003200000.0, 17.82],[-1333411200000.0, 17.54],[-1330732800000.0, 18.13],[-1328140800000.0, 18.65],[-1325462400000.0, 18.81],[-1322784000000.0, 18.87],[-1320278400000.0, 19.94],[-1317600000000.0, 21.26],[-1315008000000.0, 21.83],[-1312329600000.0, 20.91],[-1309737600000.0, 21.08],[-1307059200000.0, 21.76],[-1304380800000.0, 23.0],[-1301788800000.0, 23.58],[-1299110400000.0, 25.12],[-1296518400000.0, 25.3],[-1293840000000.0, 27.08],[-1291161600000.0, 27.13],[-1288742400000.0, 27.68],[-1286064000000.0, 27.57],[-1283472000000.0, 27.7],[-1280793600000.0, 27.94],[-1278201600000.0, 29.93],[-1275523200000.0, 31.48],[-1272844800000.0, 32.56],[-1270252800000.0, 28.96],[-1267574400000.0, 21.17],[-1264982400000.0, 22.01],[-1262304000000.0, 22.31],[-1259625600000.0, 23.7],[-1257206400000.0, 24.59],[-1254528000000.0, 25.84],[-1251936000000.0, 24.31],[-1249257600000.0, 21.87],[-1246665600000.0, 21.55],[-1243987200000.0, 21.3],[-1241308800000.0, 21.07],[-1238716800000.0, 18.21],[-1236038400000.0, 16.94],[-1233446400000.0, 16.06],[-1230768000000.0, 16.71],[-1228089600000.0, 18.16],[-1225670400000.0, 18.58],[-1222992000000.0, 16.87],[-1220400000000.0, 15.4],[-1217721600000.0, 15.06],[-1215129600000.0, 15.52],[-1212451200000.0, 15.01],[-1209772800000.0, 12.82],[-1207180800000.0, 11.15],[-1204502400000.0, 11.42],[-1201910400000.0, 9.31],[-1199232000000.0, 9.31],[-1196553600000.0, 9.34],[-1194048000000.0, 9.41],[-1191369600000.0, 7.19],[-1188777600000.0, 6.39],[-1186099200000.0, 5.57],[-1183507200000.0, 5.84],[-1180828800000.0, 8.83],[-1178150400000.0, 9.76],[-1175558400000.0, 8.48],[-1172880000000.0, 8.46],[-1170288000000.0, 8.26],[-1167609600000.0, 8.73],[-1164931200000.0, 7.83],[-1162512000000.0, 7.87],[-1159833600000.0, 8.72],[-1157241600000.0, 11.25],[-1154563200000.0, 13.1],[-1151971200000.0, 13.75],[-1149292800000.0, 13.0],[-1146614400000.0, 12.92],[-1144022400000.0, 11.7],[-1141344000000.0, 12.01],[-1138752000000.0, 12.28],[-1136073600000.0, 13.03],[-1133395200000.0, 13.93],[-1130976000000.0, 13.25],[-1128297600000.0, 13.52],[-1125705600000.0, 12.18],[-1123027200000.0, 12.29],[-1120435200000.0, 11.74],[-1117756800000.0, 11.32],[-1115078400000.0, 10.91],[-1112486400000.0, 11.11],[-1109808000000.0, 11.45],[-1107216000000.0, 11.64],[-1104537600000.0, 11.5],[-1101859200000.0, 11.09],[-1099440000000.0, 10.4],[-1096761600000.0, 11.1],[-1094169600000.0, 11.99],[-1091491200000.0, 12.54],[-1088899200000.0, 13.2],[-1086220800000.0, 14.11],[-1083542400000.0, 14.42],[-1080950400000.0, 14.83],[-10782720

In [79]:
with open("s.json", "w") as outfile:
    outfile.write(s)

In [1]:
from yahoo_fin import stock_info as si
a = si.get_data("CL=F")

In [2]:
a

,open,high,low,close,adjclose,volume,ticker
2000-08-23,31.950001,32.799999,31.950001,32.049999,32.049999,79385.0,CL=F
2000-08-24,31.900000,32.240002,31.400000,31.629999,31.629999,72978.0,CL=F
2000-08-25,31.700001,32.099998,31.320000,32.049999,32.049999,44601.0,CL=F
2000-08-28,32.040001,32.919998,31.860001,32.869999,32.869999,46770.0,CL=F
2000-08-29,32.820000,33.029999,32.560001,32.720001,32.720001,49131.0,CL=F
...,...,...,...,...,...,...,...
2022-03-10,110.410004,114.879997,105.529999,106.019997,106.019997,437924.0,CL=F
2022-03-11,105.989998,110.290001,104.480003,109.330002,109.330002,368194.0,CL=F
2022-03-14,109.419998,109.720001,99.760002,103.010002,103.010002,368194.0,CL=F
2022-03-15,NaN,NaN,NaN,NaN,NaN,NaN,CL=F
2022-03-16,95.230003,99.220001,94.900002,98.120003,98.120003,49525.0,CL=F

In [3]:
a['close']

2000-08-23     32.049999
2000-08-24     31.629999
2000-08-25     32.049999
2000-08-28     32.869999
2000-08-29     32.720001
                 ...
2022-03-10    106.019997
2022-03-11    109.330002
2022-03-14    103.010002
2022-03-15           NaN
2022-03-16     98.120003
Name: close, Length: 5491, dtype: float64

In [6]:
a_reset = a['close'].reset_index()

In [7]:
a_reset

          index       close
0    2000-08-23   32.049999
1    2000-08-24   31.629999
2    2000-08-25   32.049999
3    2000-08-28   32.869999
4    2000-08-29   32.720001
...         ...         ...
5486 2022-03-10  106.019997
5487 2022-03-11  109.330002
5488 2022-03-14  103.010002
5489 2022-03-15         NaN
5490 2022-03-16   98.120003

[5491 rows x 2 columns]

In [25]:
t = quandl.get("USTREASURY/YIELD")

In [26]:
t

,1 MO,2 MO,3 MO,6 MO,1 YR,2 YR,3 YR,5 YR,7 YR,10 YR,20 YR,30 YR
Date,,,,,,,,,,,,
1990-01-02,NaN,NaN,7.83,7.89,7.81,7.87,7.90,7.87,7.98,7.94,NaN,8.00
1990-01-03,NaN,NaN,7.89,7.94,7.85,7.94,7.96,7.92,8.04,7.99,NaN,8.04
1990-01-04,NaN,NaN,7.84,7.90,7.82,7.92,7.93,7.91,8.02,7.98,NaN,8.04
1990-01-05,NaN,NaN,7.79,7.85,7.79,7.90,7.94,7.92,8.03,7.99,NaN,8.06
1990-01-08,NaN,NaN,7.79,7.88,7.81,7.90,7.95,7.92,8.05,8.02,NaN,8.09
...,...,...,...,...,...,...,...,...,...,...,...,...
2022-01-31,0.03,0.13,0.22,0.49,0.78,1.18,1.39,1.62,1.75,1.79,2.17,2.11
2022-02-01,0.04,0.10,0.19,0.48,0.78,1.18,1.39,1.63,1.76,1.81,2.19,2.12
2022-02-02,0.04,0.10,0.19,0.45,0.76,1.16,1.38,1.60,1.74,1.78,2.17,2.11
2022-02-03,0.03,0.15,0.20,0.48,0.78,1.19,1.42,1.66,1.78,1.82,2.20,2.14
2022-02-04,0.05,0.12,0.23,0.56,0.89,1.31,1.55,1.78,1.90,1.93,2.29,2.23

In [10]:
from fredapi import Fred
fred = Fred(api_key='d79cebb1e12819cd44ed96cc291f0f72')
data = fred.get_series('SP500')

In [17]:
data

2012-03-19    1409.75
2012-03-20    1405.52
2012-03-21    1402.89
2012-03-22    1392.78
2012-03-23    1397.11
               ...
2022-03-10    4259.52
2022-03-11    4204.31
2022-03-14    4173.11
2022-03-15    4262.45
2022-03-16    4357.86
Length: 2608, dtype: float64

In [23]:
 yieldSpread = fred.get_series('T10Y2Y')

In [24]:
yieldSpread

1976-06-01    0.68
1976-06-02    0.71
1976-06-03    0.70
1976-06-04    0.77
1976-06-07    0.79
              ...
2022-03-11    0.25
2022-03-14    0.27
2022-03-15    0.30
2022-03-16    0.24
2022-03-17    0.26
Length: 11948, dtype: float64

In [31]:
# https://home.treasury.gov/policy-issues/financing-the-government/interest-rate-statistics/legacy-interest-rate-xml-and-xsd-files

import xml.etree.ElementTree as ET
tree = ET.parse('yield.xml')
root = tree.getroot()

In [39]:
for child in root:
    print(child.tag, child.attrib)

LIST_G_WEEK_OF_MONTH {}
CF_YEARHIGH_1MONTH_RATE {}
CP_YEARHIGH_1MONTH_DATE {}
CF_YEARHIGH_2MONTH_RATE {}
CP_YEARHIGH_2MONTH_DATE {}
CF_YEARHIGH_3MONTH_RATE {}
CP_YEARHIGH_3MONTH_DATE {}
CF_YEARHIGH_6MONTH_RATE {}
CP_YEARHIGH_6MONTH_DATE {}
CF_YEARHIGH_1YEAR_RATE {}
CP_YEARHIGH_1YEAR_DATE {}
CF_YEARHIGH_2YEAR_RATE {}
CP_YEARHIGH_2YEAR_DATE {}
CF_YEARHIGH_3YEAR_RATE {}
CP_YEARHIGH_3YEAR_DATE {}
CF_YEARHIGH_5YEAR_RATE {}
CP_YEARHIGH_5YEAR_DATE {}
CF_YEARHIGH_7YEAR_RATE {}
CP_YEARHIGH_7YEAR_DATE {}
CF_YEARHIGH_10YEAR_RATE {}
CP_YEARHIGH_10YEAR_DATE {}
CF_YEARHIGH_20YEAR_RATE {}
CP_YEARHIGH_20YEAR_DATE {}
CF_YEARHIGH_30YEAR_RATE {}
CP_YEARHIGH_30YEAR_DATE {}
CF_YEARLOW_1MONTH_RATE {}
CP_YEARLOW_1MONTH_DATE {}
CF_YEARLOW_2MONTH_RATE {}
CP_YEARLOW_2MONTH_DATE {}
CF_YEARLOW_3MONTH_RATE {}
CP_YEARLOW_3MONTH_DATE {}
CF_YEARLOW_6MONTH_RATE {}
CP_YEARLOW_6MONTH_DATE {}
CF_YEARLOW_1YEAR_RATE {}
CP_YEARLOW_1YEAR_DATE {}
CF_YEARLOW_2YEAR_RATE {}
CP_YEARLOW_2YEAR_DATE {}
CF_YEARLOW_3YEAR_RATE {}
CP_YEARLOW_3YEAR_DATE {}
CF_YEARLOW_5YEAR_RATE {}
CP_YEARLOW_5YEAR_DATE {}
CF_YEARLOW_7YEAR_RATE {}
CP_YEARLOW_7YEAR_DATE {}
CF_YEARLOW_10YEAR_RATE {}
CP_YEARLOW_10YEAR_DATE {}
CF_YEARLOW_20YEAR_RATE {}
CP_YEARLOW_20YEAR_DATE {}
CF_YEARLOW_30YEAR_RATE {}
CP_YEARLOW_30YEAR_DATE {}
CF_ALLTIMEHIGH_1MONTH_RATE {}
CP_ALLTIMEHIGH_1MONTH_DATE {}
CF_ALLTIMEHIGH_2MONTH_RATE {}
CP_ALLTIMEHIGH_2MONTH_DATE {}
CF_ALLTIMEHIGH_3MONTH_RATE {}
CP_ALLTIMEHIGH_3MONTH_DATE {}
CF_ALLTIMEHIGH_6MONTH_RATE {}
CP_ALLTIMEHIGH_6MONTH_DATE {}
CF_ALLTIMEHIGH_1YEAR_RATE {}
CP_ALLTIMEHIGH_1YEAR_DATE {}
CF_ALLTIMEHIGH_2YEAR_RATE {}
CP_ALLTIMEHIGH_2YEAR_DATE {}
CF_ALLTIMEHIGH_3YEAR_RATE {}
CP_ALLTIMEHIGH_3YEAR_DATE {}
CF_ALLTIMEHIGH_5YEAR_RATE {}
CP_ALLTIMEHIGH_5YEAR_DATE {}
CF_ALLTIMEHIGH_7YEAR_RATE {}
CP_ALLTIMEHIGH_7YEAR_DATE {}
CF_ALLTIMEHIGH_10YEAR_RATE {}
CP_ALLTIMEHIGH_10YEAR_DATE {}
CF_ALLTIMEHIGH_20YEAR_RATE {}
CP_ALLTIMEHIGH_20YEAR_DATE {}
CF_ALLTIMEHIGH_30YEAR_RATE {}
CP_ALLTIMEHIGH_30YEAR_DATE {}
CF_ALLTIMELOW_1MONTH_RATE {}
CP_ALLTIMELOW_1MONTH_DATE {}
CF_ALLTIMELOW_2MONTH_RATE {}
CP_ALLTIMELOW_2MONTH_DATE {}
CF_ALLTIMELOW_3MONTH_RATE {}
CP_ALLTIMELOW_3MONTH_DATE {}
CF_ALLTIMELOW_6MONTH_RATE {}
CP_ALLTIMELOW_6MONTH_DATE {}
CF_ALLTIMELOW_1YEAR_RATE {}
CP_ALLTIMELOW_1YEAR_DATE {}
CF_ALLTIMELOW_2YEAR_RATE {}
CP_ALLTIMELOW_2YEAR_DATE {}
CF_ALLTIMELOW_3YEAR_RATE {}
CP_ALLTIMELOW_3YEAR_DATE {}
CF_ALLTIMELOW_5YEAR_RATE {}
CP_ALLTIMELOW_5YEAR_DATE {}
CF_ALLTIMELOW_7YEAR_RATE {}
CP_ALLTIMELOW_7YEAR_DATE {}
CF_ALLTIMELOW_10YEAR_RATE {}
CP_ALLTIMELOW_10YEAR_DATE {}
CF_ALLTIMELOW_20YEAR_RATE {}
CP_ALLTIMELOW_20YEAR_DATE {}
CF_ALLTIMELOW_30YEAR_RATE {}
CP_ALLTIMELOW_30YEAR_DATE {}

In [40]:
cpi = fred.get_series('CPIAUCSL')
cpi

1947-01-01     21.480
1947-02-01     21.620
1947-03-01     22.000
1947-04-01     22.000
1947-05-01     21.950
               ...
2021-10-01    276.590
2021-11-01    278.524
2021-12-01    280.126
2022-01-01    281.933
2022-02-01    284.182
Length: 902, dtype: float64

In [49]:
cpi.pct_change(periods=12)*100

1947-01-01         NaN
1947-02-01         NaN
1947-03-01         NaN
1947-04-01         NaN
1947-05-01         NaN
                ...
2021-10-01    6.236941
2021-11-01    6.828372
2021-12-01    7.096542
2022-01-01    7.525934
2022-02-01    7.912024
Length: 902, dtype: float64

In [50]:
coreCPI = fred.get_series('CPILFESL')
coreCPIYOY = coreCPI.pct_change(periods=12)*100
coreCPIYOY

1957-01-01         NaN
1957-02-01         NaN
1957-03-01         NaN
1957-04-01         NaN
1957-05-01         NaN
                ...
2021-10-01    4.593958
2021-11-01    4.952634
2021-12-01    5.476621
2022-01-01    6.040783
2022-02-01    6.415744
Length: 782, dtype: float64

In [11]:
realYield = coreCPI = fred.get_series('DFII10')
realYield

2003-01-02    2.43
2003-01-03    2.43
2003-01-06    2.46
2003-01-07    2.42
2003-01-08    2.29
              ...
2022-03-11   -0.94
2022-03-14   -0.79
2022-03-15   -0.69
2022-03-16   -0.61
2022-03-17   -0.71
Length: 5011, dtype: float64

In [1]:
# https://colab.research.google.com/drive/1S7bAG8HAJ6B-KkWlClmeOAc9V9HJOPZB?usp=sharing#scrollTo=ti8GH8YikINi

import yfinance as yf
import pandas as pd
payload = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
sp500_table = payload[0]
sp500_table

,Symbol,Security,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
0,MMM,3M,reports,Industrials,Industrial Conglomerates,"Saint Paul, Minnesota",1976-08-09,66740,1902
1,AOS,A. O. Smith,reports,Industrials,Building Products,"Milwaukee, Wisconsin",2017-07-26,91142,1916
2,ABT,Abbott,reports,Health Care,Health Care Equipment,"North Chicago, Illinois",1964-03-31,1800,1888
3,ABBV,AbbVie,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
4,ABMD,Abiomed,reports,Health Care,Health Care Equipment,"Danvers, Massachusetts",2018-05-31,815094,1981
...,...,...,...,...,...,...,...,...,...
500,YUM,Yum! Brands,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
501,ZBRA,Zebra,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
502,ZBH,Zimmer Biomet,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
503,ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [2]:
sp500_tickers = sp500_table.Symbol.str.upper().values
sp500_names = sp500_table.Security.values
sp500_sectors = sp500_table["GICS Sector"].values
sp500_sub_sectors = sp500_table["GICS Sub-Industry"].values

sp500_names_mapping = dict(zip(sp500_tickers, sp500_names))
sp500_sector_mapping = dict(zip(sp500_names, sp500_sectors))
sp500_sub_sector_mapping = dict(zip(sp500_names, sp500_sub_sectors))

In [3]:
tickers = list(sp500_tickers)
prices = yf.download(tickers, start="2020-01-01", end="2021-12-31", interval='1d')
prices = prices["Adj Close"]
prices = prices.rename(columns=sp500_names_mapping)
prices

[*********************100%***********************]  505 of 505 completed

3 Failed downloads:
- CEG: Data doesn't exist for startDate = 1577808000, endDate = 1640880000
- BF.B: No data found for this date range, symbol may be delisted
- BRK.B: No data found, symbol may be delisted

,Agilent Technologies,American Airlines Group,Advance Auto Parts,Apple,AbbVie,AmerisourceBergen,Abiomed,Abbott,Accenture,Adobe,...,Wynn Resorts,Xcel Energy,ExxonMobil,Dentsply Sirona,Xylem,Yum! Brands,Zimmer Biomet,Zebra,Zions Bancorp,Zoetis
Date,,,,,,,,,,,,,,,,,,,,,
2019-12-31,84.168228,28.574404,155.080658,72.245934,79.233513,82.006271,170.589996,83.914215,204.183365,329.809998,...,137.714386,59.756420,60.208515,55.656384,76.772598,96.749886,143.179916,255.440002,48.534744,130.665115
2020-01-02,84.799675,28.982893,154.354446,73.894325,80.137344,82.064148,168.809998,84.001175,203.776093,334.429993,...,142.405029,58.711700,61.174896,55.990772,77.805458,98.132988,142.720795,259.140015,49.020840,132.432312
2020-01-03,83.438148,27.548195,154.364105,73.175926,79.376694,81.032066,166.820007,82.977112,203.436752,331.809998,...,140.292755,58.994057,60.683079,55.371174,78.263420,97.825638,142.347702,256.049988,48.329098,132.452057
2020-01-06,83.684799,27.219410,151.827209,73.759010,80.003113,82.218460,179.039993,83.411858,202.108246,333.709991,...,140.015091,58.909351,61.149021,55.676060,77.756729,97.768013,141.525040,258.010010,47.740170,131.435196
2020-01-07,83.941315,27.119778,150.026199,73.412117,79.546722,81.630089,180.350006,82.948143,197.744751,333.390015,...,140.679504,58.786999,60.648567,55.971111,77.464401,97.940918,141.400711,256.470001,47.450382,131.879440
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-12-23,157.592438,18.260000,230.452118,176.055695,131.723129,129.109039,352.209991,138.670883,402.267090,569.619995,...,88.879997,66.148552,60.350952,55.322369,117.112770,134.714600,123.051254,582.409973,62.041107,242.121170
2021-12-27,158.531204,18.170000,234.790527,180.100540,133.029587,131.471329,357.829987,140.962799,414.255981,577.679993,...,87.580002,66.357094,61.211414,55.841362,117.900162,137.372253,124.087379,606.330017,62.687782,246.114746
2021-12-28,158.970612,18.540001,236.408752,179.061859,133.009781,131.929840,357.440002,139.976273,414.196136,569.359985,...,86.459999,67.151550,61.013607,55.921204,119.126106,137.342392,124.475731,597.320007,62.787273,243.858383
2021-12-29,160.438675,18.049999,239.287781,179.151749,133.969818,132.906647,361.839996,140.693741,414.345795,569.289978,...,84.980003,67.489197,60.479530,56.540001,118.966637,138.019257,124.495148,601.119995,63.125534,246.633926
2021-12-30,160.668396,18.070000,235.803162,177.973251,134.533966,133.335266,362.059998,140.504410,412.759857,570.530029,...,86.150002,67.757332,60.123474,56.200001,118.707489,137.750504,124.533981,597.539978,62.807171,244.766922

In [4]:
prices.to_csv('sp500prices.csv')

In [2]:
import investpy
data = investpy.economic_calendar(from_date='01/03/2022', to_date='01/09/2022')
data

,id,date,time,zone,currency,importance,event,actual,forecast,previous
0,173,01/03/2022,All Day,south korea,None,None,South Korea - Independence Day,None,None,None
1,202,01/03/2022,All Day,argentina,None,None,Argentina - Carnival,None,None,None
2,202,01/03/2022,All Day,brazil,None,None,Brazil - Carnival,None,None,None
3,202,01/03/2022,All Day,venezuela,None,None,Venezuela - Carnival,None,None,None
4,202,01/03/2022,All Day,ecuador,None,None,Ecuador - Carnival,None,None,None
...,...,...,...,...,...,...,...,...,...,...
2911,216,31/08/2022,All Day,malaysia,None,None,Malaysia - National Day,None,None,None
2912,247,31/08/2022,All Day,india,None,None,India - Ganesh Chaturthi,None,None,None
2913,178,01/09/2022,All Day,slovakia,None,None,Slovakia - Constitution Day,None,None,None
2914,215,01/09/2022,All Day,vietnam,None,None,Vietnam - Public Holiday,None,None,None
2915,247,01/09/2022,All Day,mauritius,None,None,Mauritius - Ganesh Chaturthi,None,None,None

In [5]:
dvdYield = quandl.get("MULTPL/SP500_DIV_YIELD_MONTH")
dvdYield

            Value
Date
1871-01-31   5.86
1871-02-28   5.78
1871-03-31   5.64
1871-04-30   5.49
1871-05-31   5.35
...           ...
2021-12-31   1.29
2022-01-31   1.32
2022-02-01   1.33
2022-02-28   1.32
2022-03-01   1.40

[1834 rows x 1 columns]

In [6]:
earnings = quandl.get("MULTPL/SP500_EARNINGS_MONTH")
earnings

             Value
Date
1871-01-31    9.03
1871-02-28    8.76
1871-03-31    8.63
1871-04-30    8.95
1871-05-31    9.17
...            ...
2021-05-31  155.17
2021-06-30  164.28
2021-07-31  169.20
2021-08-31  174.54
2021-09-30  179.74

[1809 rows x 1 columns]

In [7]:
earningYield = quandl.get("MULTPL/SP500_EARNINGS_YIELD_MONTH")
earningYield

            Value
Date
1871-01-01   9.01
1871-02-01   8.89
1871-03-01   8.68
1871-04-01   8.44
1871-05-01   8.23
...           ...
2022-01-01   3.83
2022-01-31   3.88
2022-02-01   3.82
2022-02-28   4.01
2022-03-01   4.07

[1836 rows x 1 columns]

In [14]:
import dbnomics
df = dbnomics.fetch_series('WB', 'WDI', 'NY.GDP.MKTP.KD.ZG-1W')
df

,@frequency,provider_code,dataset_code,dataset_name,series_code,series_name,original_period,period,original_value,value,indicator,country,indicator (label),country (label)
0,annual,WB,WDI,World Development Indicators,NY.GDP.MKTP.KD.ZG-1W,GDP growth (annual %) â€“ World,1960,1960-01-01,NA,NaN,NY.GDP.MKTP.KD.ZG,1W,GDP growth (annual %),World
1,annual,WB,WDI,World Development Indicators,NY.GDP.MKTP.KD.ZG-1W,GDP growth (annual %) â€“ World,1961,1961-01-01,3.80083,3.800832,NY.GDP.MKTP.KD.ZG,1W,GDP growth (annual %),World
2,annual,WB,WDI,World Development Indicators,NY.GDP.MKTP.KD.ZG-1W,GDP growth (annual %) â€“ World,1962,1962-01-01,5.32028,5.320280,NY.GDP.MKTP.KD.ZG,1W,GDP growth (annual %),World
3,annual,WB,WDI,World Development Indicators,NY.GDP.MKTP.KD.ZG-1W,GDP growth (annual %) â€“ World,1963,1963-01-01,5.19242,5.192421,NY.GDP.MKTP.KD.ZG,1W,GDP growth (annual %),World
4,annual,WB,WDI,World Development Indicators,NY.GDP.MKTP.KD.ZG-1W,GDP growth (annual %) â€“ World,1964,1964-01-01,6.56875,6.568749,NY.GDP.MKTP.KD.ZG,1W,GDP growth (annual %),World
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56,annual,WB,WDI,World Development Indicators,NY.GDP.MKTP.KD.ZG-1W,GDP growth (annual %) â€“ World,2016,2016-01-01,2.82457,2.824569,NY.GDP.MKTP.KD.ZG,1W,GDP growth (annual %),World
57,annual,WB,WDI,World Development Indicators,NY.GDP.MKTP.KD.ZG-1W,GDP growth (annual %) â€“ World,2017,2017-01-01,3.39464,3.394638,NY.GDP.MKTP.KD.ZG,1W,GDP growth (annual %),World
58,annual,WB,WDI,World Development Indicators,NY.GDP.MKTP.KD.ZG-1W,GDP growth (annual %) â€“ World,2018,2018-01-01,3.2627,3.262697,NY.GDP.MKTP.KD.ZG,1W,GDP growth (annual %),World
59,annual,WB,WDI,World Development Indicators,NY.GDP.MKTP.KD.ZG-1W,GDP growth (annual %) â€“ World,2019,2019-01-01,2.60215,2.602147,NY.GDP.MKTP.KD.ZG,1W,GDP growth (annual %),World
60,annual,WB,WDI,World Development Indicators,NY.GDP.MKTP.KD.ZG-1W,GDP growth (annual %) â€“ World,2020,2020-01-01,-3.3626,-3.362598,NY.GDP.MKTP.KD.ZG,1W,GDP growth (annual %),World